#include "addr.h"

#include <errno.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#ifndef _WIN32
#include <sys/un.h>
#endif

#include "../../include/dqlite.h"

static int parseService(const char *service, int *port)
{
	char *end;
	long value;

	errno = 0;
	value = strtol(service, &end, 10);
	if (errno != 0 || end == service || *end != '\0' || value < 0 ||
	    value > UINT16_MAX) {
		return DQLITE_ERROR;
	}
	*port = (int)value;
	return 0;
}

static char *dupRange(const char *start, size_t len)
{
	char *copy = malloc(len + 1);
	if (copy == NULL) {
		return NULL;
	}
	memcpy(copy, start, len);
	copy[len] = '\0';
	return copy;
}

static int parseMappedIpv4(const char *node,
			   int port,
			   struct sockaddr_in6 *addr)
{
	static const char prefix[] = "::ffff:";
	struct sockaddr_in addr_in;
	uint8_t mapped[16] = {0};
	int rv;

	if (strncmp(node, prefix, sizeof prefix - 1) != 0) {
		return DQLITE_ERROR;
	}

	rv = uv_ip4_addr(node + sizeof prefix - 1, port, &addr_in);
	if (rv != 0) {
		return DQLITE_ERROR;
	}

	mapped[10] = 0xff;
	mapped[11] = 0xff;
	memcpy(&mapped[12], &addr_in.sin_addr, sizeof addr_in.sin_addr);

	memset(addr, 0, sizeof *addr);
	addr->sin6_family = AF_INET6;
	addr->sin6_port = addr_in.sin_port;
	memcpy(&addr->sin6_addr, mapped, sizeof mapped);
	return 0;
}

int AddrParse(const char *input,
	      struct sockaddr *addr,
	      socklen_t *addr_len,
	      const char *service,
	      int flags)
{
	int rv;
	char *node = NULL;
	size_t input_len = strlen(input);
	char c = input[0];
	int port;
	struct sockaddr_in addr_in;
	struct sockaddr_in6 addr_in6;
	socklen_t required_len;
	const char *addr_start, *close_bracket, *colon, *dot;
#ifndef _WIN32
	struct sockaddr_un *addr_un;
	const char *name;
	size_t name_len;
#endif

	if (c == '@') {
#ifdef _WIN32
		(void)flags;
		return DQLITE_MISUSE;
#else
		/* Unix domain address.
		 * FIXME the use of the "abstract namespace" here is
		 * Linux-specific */
		if (!(flags & DQLITE_ADDR_PARSE_UNIX)) {
			return DQLITE_MISUSE;
		}
		addr_un = (struct sockaddr_un *)addr;
		if (*addr_len < (socklen_t)sizeof(*addr_un)) {
			return DQLITE_ERROR;
		}
		name = input + 1;
		name_len = input_len - 1;
		if (name_len == 0) {
			/* Autogenerated abstract socket name */
			addr_un->sun_family = AF_UNIX;
			*addr_len = sizeof(addr_un->sun_family);
			return 0;
		}
		/* Leading null byte, no trailing null byte */
		if (name_len + 1 > sizeof(addr_un->sun_path)) {
			return DQLITE_ERROR;
		}
		memset(addr_un->sun_path, 0, sizeof(addr_un->sun_path));
		memcpy(addr_un->sun_path + 1, name, name_len);
		addr_un->sun_family = AF_UNIX;
		*addr_len = (socklen_t)offsetof(struct sockaddr_un, sun_path) +
			    (socklen_t)name_len + 1;
		return 0;
#endif
	} else if (c == '[') {
		/* IPv6 address with port */
		addr_start = input + 1;
		close_bracket = memchr(input, ']', input_len);
		if (!close_bracket) {
			return DQLITE_ERROR;
		}
		colon = close_bracket + 1;
		if (*colon != ':') {
			return DQLITE_ERROR;
		}
		service = colon + 1;
		node = dupRange(addr_start, (size_t)(close_bracket - addr_start));
	} else if ((dot = memchr(input, '.', input_len)) != NULL &&
		   ((colon = memchr(input, ':', input_len)) == NULL ||
		    dot < colon)) {
		/* IPv4 address */
		if (colon) {
			service = colon + 1;
			node = dupRange(input, (size_t)(colon - input));
		} else {
			node = strdup(input);
		}
	} else {
		/* IPv6 address without port */
		node = strdup(input);
	}

	if (!node) {
		return DQLITE_NOMEM;
	}

	rv = parseService(service, &port);
	if (rv != 0) {
		goto err_after_strdup;
	}

	if (memchr(node, ':', strlen(node)) != NULL) {
		rv = uv_ip6_addr(node, port, &addr_in6);
		if (rv != 0) {
			rv = parseMappedIpv4(node, port, &addr_in6);
		}
		required_len = (socklen_t)sizeof addr_in6;
		if (rv != 0) {
			rv = DQLITE_ERROR;
			goto err_after_strdup;
		}
		if (required_len > *addr_len) {
			rv = DQLITE_ERROR;
			goto err_after_strdup;
		}
		memcpy(addr, &addr_in6, (size_t)required_len);
		*addr_len = required_len;
	} else {
		rv = uv_ip4_addr(node, port, &addr_in);
		required_len = (socklen_t)sizeof addr_in;
		if (rv != 0) {
			rv = DQLITE_ERROR;
			goto err_after_strdup;
		}
		if (required_len > *addr_len) {
			rv = DQLITE_ERROR;
			goto err_after_strdup;
		}
		memcpy(addr, &addr_in, (size_t)required_len);
		*addr_len = required_len;
	}

err_after_strdup:
	free(node);

	return rv;
}
