((nil . ((fill-column . 80)))
 (c-mode . ((c-file-style . "linux-tabs-only")
	    (flycheck-gcc-definitions . ("DQLITE_DEBUG" "DQLITE_EXPERIMENTAL" "_GNU_SOURCE"))
	    (flycheck-clang-definitions . ("DQLITE_DEBUG" "DQLITE_EXPERIMENTAL" "_GNU_SOURCE"))
	    (flycheck-gcc-include-path . ("../include")))))
