#!/usr/bin/python3

import os
import sys
import shutil
import subprocess
import time

BUILD_SQLITE = "./build-sqlite.sh"
BUILD_DQLITE = "go build -tags libsqlite3 .".split(" ")
BUILD_DEMO = "go build -tags libsqlite3 testdata/demo.go".split(" ")
BASE_PORT = 9980


def spawnNode(n, purge=False):
    data = "/tmp/dqlite-demo-%d" % n
    port = BASE_PORT + n

    if purge and os.path.exists(data):
        shutil.rmtree(data)

    args = ["./demo", "-data", data, "-addr", "127.0.0.1:%d" % port]
    if n > 0:
        args.extend(["-join", "127.0.0.1:%d" % BASE_PORT])

    env = os.environ.copy()
    env.update({
        "LD_LIBRARY_PATH": os.path.join(os.getcwd(), ".sqlite", ".libs"),
    })

    return subprocess.Popen(args, env=env)


if __name__ == "__main__":
    subprocess.check_call(BUILD_SQLITE)

    env = os.environ.copy()
    env.update({
        "CGO_CFLAGS": "-I%s" % os.path.join(os.getcwd(), ".sqlite"),
        "CGO_LDFLAGS": "-L%s" % os.path.join(os.getcwd(), ".sqlite", ".libs"),
    })
    subprocess.check_call(BUILD_DQLITE, env=env)
    subprocess.check_call(BUILD_DEMO, env=env)

    processes = []
    for i in range(3):
        processes.append(spawnNode(i, purge=True))

    while True:
        for i, process in enumerate(processes):
            rc = process.poll()
            if rc is not None:
                if rc != 0:
                    print("ERROR node %d exited with return code %d" % (i, rc))
                    sys.exit(1)
                # respawn
                processes[i] = spawnNode(i)
        time.sleep(0.5)
