#include "response.h"

#define RESPONSE__IMPLEMENT(LOWER, UPPER, _) \
	SERIALIZE__IMPLEMENT(response_##LOWER, RESPONSE_##UPPER);

RESPONSE__TYPES(RESPONSE__IMPLEMENT, );
SERIALIZE__IMPLEMENT(response_metadata_v0, RESPONSE_METADATA_V0);
