name: Canonical CLA

on:
  pull_request:
    branches: [master]

jobs:
  cla-check:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v2
