name: CI Tests (32-bit)

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup dependencies
      run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y gcc-multilib libsqlite3-dev:i386 liblz4-dev:i386 libuv1-dev:i386
          sudo ldconfig

    - name: Build raft
      run: |
          git clone https://github.com/canonical/raft.git --depth 1
          cd raft
          git clone https://github.com/edlund/amalgamate.git --depth 1
          amalgamate/amalgamate.py --config=amalgamation.json --source=$(pwd)
          gcc -std=gnu11 raft.c -m32 -shared -fPIC -o libraft.so -DHAVE_LINUX_AIO_ABI_H -luv -llz4

          cd ..

    - name: Build dqlite
      run: |
          autoreconf -i
          RAFT_CFLAGS=-I../raft/include RAFT_LIBS='-L../raft -lraft' LIBUV_CFLAGS= LIBUV_LIBS=-luv ./configure
          make CFLAGS=-m32 LDFLAGS=-m32
